/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPdvRouteImport } from './routes/_app.pdv'
import { Route as AppMovimentacoesRouteImport } from './routes/_app.movimentacoes'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/pdv': typeof AppPdvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/pdv': typeof AppPdvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/movimentacoes': typeof AppMovimentacoesRoute
  '/_app/pdv': typeof AppPdvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/pdv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/movimentacoes'
    | '/pdv'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/estoque'
    | '/_app/movimentacoes'
    | '/_app/pdv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pdv': {
      id: '/_app/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimentacoes': {
      id: '/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppPdvRoute: typeof AppPdvRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppPdvRoute: AppPdvRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
